### ISSUE TITLE
Does setting ContinuousIntegrationBuild also set Deterministic?

### ISSUE THREAD

**Issue by AshleighAdams** [dotnet/reproducible-builds#14]
I'm converting a project over to use this package, and I currently have something akin to:

```xml
<PropertyGroup Condition="'$(CI)' != ''">
  <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  <Deterministic>true</Deterministic>
</PropertyGroup>
```

I suspect that setting `ContinuousIntegrationBuild` is going to also set `Deterministic`?

**Comment by wapplegate** [comment]
A little late, but it looks like it sets ContinuousIntegrationBuild to true dynamically when running in a CI environment:

https://github.com/dotnet/reproducible-builds/blob/main/src/DotNet.ReproducibleBuilds/DotNet.ReproducibleBuilds.props

You can see the props file includes conditions for multiple CI systems.

**Comment by AshleighAdams** [comment]
@wapplegate Yeah, I see that, but I can't figure out if `Deterministic` will also be set to true as a consequence of `ContinuousIntegrationBuild` being set, or if I need to keep doing that one manually in my projects :(

**Comment by wapplegate** [comment]
Yeah my bad I read that a little quick. If you remove <Deterministic>true</Deterministic> does it actually make a difference? I was under the assumption it wasn't required.

**Comment by dferretti** [comment]
IIRC `Deterministic` is enabled by default nowadays:
original PR way back when: https://github.com/dotnet/sdk/pull/153
current SDK: https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L34

from a quick search in the SDK repo I don't _think_ the `ContinuousIntegrationBuild` property has anything to do with `Deterministic`

**Comment by AshleighAdams** [comment]
Looks like that's the answer @dferretti, thanks. Will close this now.
