### ISSUE TITLE
Required workaround?

### ISSUE THREAD

**Issue by olivier-spinelli** [dotnet/reproducible-builds#17]
I haven't seen this workaround in the props/targets:
https://github.com/dotnet/sdk/issues/1458#issuecomment-695119194

Shoud we add it? Couldn't it be added in a upcoming 1.1.2 version?

(I'm must admit that I'm quite lost in the NuGet/MSBuild current complexity.)

**Comment by baronfel** [comment]
Hello, I'm not sure this is the correct repo for this suggestion. This repo is primarily for build determinism and standardized sourcelink configuration, but your link is about copying PDBs from dependencies into your built/packaged outputs. Can you describe what change you think would need to be made here?

**Comment by olivier-spinelli** [comment]
You are totally right. I was hoping that this package could be a kind of NuGet fixer that could deal with all the complexity of NuGet/MSBuild. 

I'm currently fighting to settle a generic Directory.Build.props (ie. standardazing multiple repositories)... and suffering.
I'm closing this issue (sorry).
