### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by aetos382** [dotnet/reproducible-builds#31]
The NuGet package of this project was last released in November 2011.
Since then, several pull requests have been submitted and some have been merged, but no new versions of the packages have been released.
Is this project still maintained?

**Comment by kzu** [comment]
I'd also like to know. Got a PR merged but the package was never updated :( 

@baronfel @clairernovotny

**Comment by joegoldman2** [comment]
@baronfel @clairernovotny any news of an upcoming release? Thank you.

**Comment by baronfel** [comment]
@MattKotsenas and I are working the problem - we have build pipelines that can create release artifacts (in this case NuGet packages), but we're stuck on being able to approve those artifacts to publish to NuGet. Once we can figure that out, we'll document the process and ensure at least two folks have approval rights at all times to prevent this kind of delay/blockage in the future.

**Comment by aetos382** [comment]
Thank you. I'm glad to know that this project is still alive. I'm looking forward to the new release.
