### ISSUE TITLE
Version 1.2.4 of DotNet.ReproducibleBuilds no longer has SourceLink as dependencies

### ISSUE THREAD

**Issue by rsking** [dotnet/reproducible-builds#44]
The latest release of `DotNet.ReproducibleBuilds` (1.2.4), does not have dependencies on the SourceLink packages.

Version 1.2.4 -> https://www.nuget.org/packages/DotNet.ReproducibleBuilds/1.2.4#dependencies-body-tab

Version 1.1.1 -> https://www.nuget.org/packages/DotNet.ReproducibleBuilds/1.1.1#dependencies-body-tab

**Comment by baronfel** [comment]
That's partially on purpose - as of .NET 8 SourceLink is included in the .NET SDK, so it's no longer necessary for this package to bring it. Since NuGet dependencies can't be gated by SDK version, we opted to remove them entirely from this package.

**Comment by rsking** [comment]
Fair enough, that does work. Was not obvious from the release that this was intended.
