### ISSUE TITLE
RepositoryBranch logic conflicts with .NET 9 SDK

### ISSUE THREAD

**Issue by MattKotsenas** [dotnet/reproducible-builds#46]
We have custom logic to set the repository branch name based on CI provider environment variables (see https://github.com/dotnet/reproducible-builds/blob/97f31844f6ea0f74f334ccb35609cf6e52bb25a3/src/DotNet.ReproducibleBuilds/DotNet.ReproducibleBuilds.targets#L16)

However, our logic strips the `refs/heads/` and `refs/tags/` from the branch name, which conflicts with https://github.com/NuGet/NuGet.Client/pull/5923 available in the .NET 9 SDK, which gives the full ref name.

I think we should update our logic to also use the full ref name:

1. for consistency with the SDK
2. for reproducibility (so packages are tagged the same locally and in CI)

**Comment by baronfel** [comment]
We dug into this a bit and we should make this change. There are some users who are explicitly setting values like `main`, `master`, or using tools like GitVersion to get the repository branch - .NET 9's changes won't overwrite these values, and we should have a goal in this repo of upstreaming things that prove their value in this repo. This is a success story!
